# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias c='clear'
alias ra='joshuto'

export PATH="/root/opt/bin:$PATH"

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi
